tradesAppPackage/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{000000}</displayFormat>
        <label>Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tradesAppPackage/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tradesAppPackage/main/default/objects/Trade__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Date Booked</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

tradesAppPackage/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tradesAppPackage/main/default/classes/createPostChatter.cls
public with sharing class createPostChatter {

    public static void tradePostChatter(List<Trade__c> tradeList) {

        List<User> lstUser = [SELECT Id FROM User WHERE Id IN (SELECT UserOrGroupId FROM GroupMember WHERE Group.DeveloperName = 'Trade_reviewers')];

        if(lstUser.size()>0){

            List<FeedItem> lstFeedItem = new List<FeedItem>();
        
            for(Trade__c trade : tradeList){
    
                String bodyFeeItem = 'A new trade has been created with the following data: '+ '\n';
                bodyFeeItem += 'Sell Currency: ' + trade.Sell_Currency__c + '\n';
                bodyFeeItem += 'Sell Amount: ' + trade.Sell_Amount__c + '\n';
                bodyFeeItem += 'Buy Currency: ' + trade.Buy_Currency__c + '\n';
                bodyFeeItem += 'Buy Amount: ' + trade.Buy_Amount__c + '\n';
                bodyFeeItem += 'Rate: ' + trade.Rate__c + '\n';
                bodyFeeItem += 'Booked Date: ' + trade.Date_Booked__c + '\n';
                bodyFeeItem += 'Link to the trade: ' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + trade.Id;

                for(User u : lstUser){
                    FeedItem item = new FeedItem(
                        parentId = u.id, // where to post message
                        body = bodyFeeItem
                    ); 
                    lstFeedItem.add(item);
                }
    
            }

            if(lstFeedItem.size()>0){
                insert lstFeedItem;
            }

        }

    }

}