tradesAppPackage/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{000000}</displayFormat>
        <label>Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tradesAppPackage/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tradesAppPackage/main/default/objects/Trade__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Date Booked</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

tradesAppPackage/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tradesAppPackage/main/default/classes/tradeTriggerTest.cls
@isTest
public class tradeTriggerTest {

    @testSetup static void setup() {
        
        Group tradeReviewersGroup = [Select ID from Group where DeveloperName = 'Trade_reviewers'];

        User u = new User(FirstName = 'My', LastName = 'User', 
                           Alias = 'myuse', Email = 'my.user@email.com',
                           Username = 'my.user@email.com', CommunityNickname = 'MyUser',
                           ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id, TimeZoneSidKey = 'Europe/Rome',
                           LocaleSidKey = 'ES', EmailEncodingKey = 'UTF-8',
                           LanguageLocaleKey = 'es', IsActive = true);
        insert u;

        GroupMember member = new GroupMember();
        member.UserOrGroupId = u.Id;
        member.GroupId = tradeReviewersGroup.Id;
        insert member;

    }

    @isTest 
    static void newTrade() {

        Test.startTest();
        Trade__c trade = new Trade__c();
        trade.Sell_Currency__c = 'EUR';
        trade.Sell_Amount__c = 5.10;
        trade.Buy_Currency__c = 'USD';
        trade.Rate__c = 0.99;
        trade.Date_Booked__c = system.now();
        trade.Buy_Amount__c = trade.Sell_Amount__c * trade.Rate__c;
        insert trade;
        Test.stopTest();

    }
}